repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      files: backend/.*\.py$
      exclude: src/app/migrations/

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 5.13.2
  hooks:
    - id: isort
      files: backend/.*\.py$
      exclude: src/app/migrations/
